essaye affichage

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,8 +25,10 @@ jobs:
           cache: 'maven'
       - name: Build and Test
         run: |
-          echo "Using MAVEN_OPTS: $MAVEN_OPTS"
           export MAVEN_OPTS="-Xms512m -XX:+UseG1GC -XX:+PrintGCDetails -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCompressedOops"
+          echo "Using MAVEN_OPTS: $MAVEN_OPTS"
+          xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage || { echo "Maven build failed"; exit 1; }
+          echo "Maven build completed successfully"
           xvfb-run mvn -B verify -Djavafx.platform=linux jacoco:report -Pcoverage
           unset MAVEN_OPTS
       - name: Get JaCoCo Coverage
